name: PandoraCrates
version: ${project.version}
main: me.nanigans.pandoracrates.PandoraCrates
authors: [ProNanigans]
description: Pandora Crates plugin
depend: [HolographicDisplays]
commands:
  keygive:
    usage: /keygive <player> <key name> <amount>
    description: Gives the player a key
  createcrate:
    usage: /createcrate <crate name>
    description: Creates a new crate where you stand
  lootbaggive:
    usage: /lootbaggive <player> <bat name>
    description: Gives a new lootbag to the player
permissions:
  Crates.KeyGive:
    description: Allows the user to give out new keys
    default: op
  Crates.CreateCrate:
    description: Allows the user to create a new crate
    default: op
  LootBag.Give:
    description: Allows the user to create a new loot bag
    default: op
