name: PandoraCrates
version: ${project.version}
main: me.nanigans.pandoracrates.PandoraCrates
authors: [ProNanigans]
description: Pandora Crates plugin
depend: [HolographicDisplays]
commands:
  keygive:
    usage: /keygive <player> <key name> <amount>
    description: Gives the player a key
  createcrate:
    usage: /createcrate <crate name>
    description: Crates a new crate where you stand
permissions:
  Crates.KeyGive:
    description: Allows the user to give out new keys
    default: op
  Crates.CreateCrate:
    description: Allows the user to create a new crate
    default: op
